CC = gcc
FLAGS = -std=c11 -Wpedantic -Wall -Wextra -Werror -O2 -I include
TARGET = SelectionSort
SRC = src/main.c src/SelectionSort.c

default: compile

compile:
	$(CC) $(FLAGS) $(SRC) -o $(TARGET)
	
