CC = gcc
FLAGS = -std=c11 -Wpedantic -Wall -Wextra -Werror -O2 -I include
TARGET = InsertionSort
SRC = src/main.c src/InsertionSort.c

default: compile

compile:
	$(CC) $(FLAGS) $(SRC) -o $(TARGET)
	
