CC = gcc
FLAGS = -std=c11 -Wpedantic -Wall -Wextra -Werror -O2 -I include
TARGET = BinarySearch
	SRC = src/main.c src/BinarySearchTree.c

default: compile

compile:
	$(CC) $(FLAGS) $(SRC) -o $(TARGET)
